# Generated by Django 3.2.3 on 2021-06-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210528_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
